### ISSUE TITLE
New Metrics

### ISSUE THREAD

**Issue by vollmersj** [Vollmer-Lab/survival_fairness#3]
- [ ] wasserstein implementation in R (or [reimplement](https://stackoverflow.com/questions/65175268/1d-wasserstein-distance-in-python) )
 - [ ] time weighted

**Comment by ashryaagr** [comment]
https://www.rdocumentation.org/packages/transport/versions/0.12-2/topics/wasserstein
The transport library in R already has a wasserstein implementation which we can use
