### ISSUE TITLE
Integrating the project with a survival analysis R toolkit

### ISSUE THREAD

**Issue by ashryaagr** [Vollmer-Lab/survival_fairness#5]
Instead of writing code from scratch, it might be better to work with a survival analysis toolkit. These two seem to be 2 choices we have for this.
- https://github.com/kassambara/survminer
- https://github.com/therneau/survival

If we decide to use a toolkit, following is the breakdown of tasks for integration of project with the toolkit:
- [ ] Port dataset currently in this Repository to the toolkit
- [ ] Create hazard rate for fairness analysis

**Comment by RaphaelS1** [comment]
I would suggest mlr3proba (simulation with e.g. `simsurv`) and mlr3fairness as well (especially as me and @pfistfl ) can help with this
